/**
 * CodeVigil — Malicious Pattern Definitions
 * 40+ detection rules organized by category
 */

export const SEVERITY = {
  CRITICAL: 'critical',
  HIGH: 'high',
  MEDIUM: 'medium',
  LOW: 'low',
  INFO: 'info',
};

export const CATEGORY = {
  CODE_EXEC: 'Code Execution & Obfuscation',
  NETWORK: 'Network Exfiltration',
  FILE_ACCESS: 'File System Access',
  PROCESS: 'Process Execution',
  CRYPTO: 'Crypto / Wallet Specific',
  SOCIAL: 'Social Engineering',
};

export const CATEGORY_ICONS = {
  [CATEGORY.CODE_EXEC]: '⚡',
  [CATEGORY.NETWORK]: '🌐',
  [CATEGORY.FILE_ACCESS]: '📂',
  [CATEGORY.PROCESS]: '⚙️',
  [CATEGORY.CRYPTO]: '🔐',
  [CATEGORY.SOCIAL]: '🎭',
};

/**
 * Each pattern has:
 * - id: unique identifier
 * - name: human-friendly label
 * - category: one of CATEGORY
 * - severity: one of SEVERITY
 * - confidence: 0-1 (how likely this pattern alone indicates malice)
 * - regex: RegExp to match against code
 * - description: why it's dangerous
 * - remediation: what the developer should do
 */
export const PATTERNS = [
  // ── Code Execution & Obfuscation ──────────────────────
  {
    id: 'eval_usage',
    name: 'eval() Usage',
    category: CATEGORY.CODE_EXEC,
    severity: SEVERITY.CRITICAL,
    confidence: 0.85,
    regex: /\beval\s*\(/gi,
    description: 'eval() executes arbitrary strings as code. Attackers use it to run obfuscated payloads that bypass static analysis.',
    remediation: 'Replace eval() with safer alternatives like JSON.parse() for data or explicit function calls for logic.',
  },
  {
    id: 'function_constructor',
    name: 'Function() Constructor',
    category: CATEGORY.CODE_EXEC,
    severity: SEVERITY.CRITICAL,
    confidence: 0.9,
    regex: /new\s+Function\s*\(/gi,
    description: 'The Function constructor creates functions from strings, effectively acting as eval(). Often used to bypass eval() detection.',
    remediation: 'Define functions explicitly. Avoid constructing functions from dynamic strings.',
  },
  {
    id: 'base64_decode_exec',
    name: 'Base64 Decode + Execution',
    category: CATEGORY.CODE_EXEC,
    severity: SEVERITY.CRITICAL,
    confidence: 0.95,
    regex: /(?:Buffer\.from|atob)\s*\([^)]*(?:base64|'|")[^)]*\)[\s\S]{0,50}(?:eval|Function|exec|spawn)/gi,
    description: 'Decoding base64 strings and passing them to execution functions is a classic malware obfuscation technique.',
    remediation: 'Never execute decoded base64 content. Inspect the encoded content manually to verify its purpose.',
  },
  {
    id: 'atob_usage',
    name: 'atob() Decoding',
    category: CATEGORY.CODE_EXEC,
    severity: SEVERITY.MEDIUM,
    confidence: 0.5,
    regex: /\batob\s*\(/gi,
    description: 'atob() decodes base64 strings. While legitimate uses exist, malware frequently uses it to hide payloads.',
    remediation: 'Verify that the base64 content is known and safe. Check what happens with the decoded output.',
  },
  {
    id: 'hex_encoded_strings',
    name: 'Hex-Encoded Strings',
    category: CATEGORY.CODE_EXEC,
    severity: SEVERITY.HIGH,
    confidence: 0.7,
    regex: /(?:\\x[0-9a-fA-F]{2}){4,}/g,
    description: 'Long hex-encoded strings are commonly used to obfuscate URLs, filenames, and commands in malicious code.',
    remediation: 'Decode the hex sequence to inspect its actual content.',
  },
  {
    id: 'string_concat_obfuscation',
    name: 'String Concatenation Obfuscation',
    category: CATEGORY.CODE_EXEC,
    severity: SEVERITY.HIGH,
    confidence: 0.65,
    regex: /(?:['"][a-z]{1,4}['"]\s*\+\s*){2,}['"][a-z]{1,4}['"]/gi,
    description: 'Breaking strings into small concatenated pieces (like "ev"+"al") is used to evade keyword detection.',
    remediation: 'Evaluate the concatenated result. If it forms a dangerous function name (eval, exec), treat it as malicious.',
  },
  {
    id: 'settimeout_string',
    name: 'setTimeout/setInterval with String',
    category: CATEGORY.CODE_EXEC,
    severity: SEVERITY.HIGH,
    confidence: 0.8,
    regex: /(?:setTimeout|setInterval)\s*\(\s*['"`]/gi,
    description: 'Passing a string to setTimeout/setInterval acts like eval(), executing the string as code.',
    remediation: 'Always pass a function reference to setTimeout/setInterval, never a string.',
  },
  {
    id: 'document_write',
    name: 'document.write() Injection',
    category: CATEGORY.CODE_EXEC,
    severity: SEVERITY.MEDIUM,
    confidence: 0.55,
    regex: /document\.write(?:ln)?\s*\(/gi,
    description: 'document.write() can inject arbitrary HTML/scripts. Malware uses it to load external payloads.',
    remediation: 'Use DOM manipulation methods (createElement, appendChild) instead of document.write().',
  },

  // ── Network Exfiltration ──────────────────────────────
  {
    id: 'fetch_suspicious',
    name: 'fetch() to External URL',
    category: CATEGORY.NETWORK,
    severity: SEVERITY.HIGH,
    confidence: 0.6,
    regex: /fetch\s*\(\s*['"`]https?:\/\//gi,
    description: 'HTTP requests to external URLs can exfiltrate sensitive data like environment variables, keys, or tokens.',
    remediation: 'Verify the destination URL is trusted. Check the request payload for sensitive data.',
  },
  {
    id: 'webhook_urls',
    name: 'Webhook URL (Discord/Telegram)',
    category: CATEGORY.NETWORK,
    severity: SEVERITY.CRITICAL,
    confidence: 0.95,
    regex: /(?:discord(?:app)?\.com\/api\/webhooks|api\.telegram\.org\/bot)/gi,
    description: 'Discord webhooks and Telegram bot APIs are commonly used by malware to exfiltrate stolen data to attacker-controlled channels.',
    remediation: 'This is almost certainly malicious. Report the webhook URL and do not run the code.',
  },
  {
    id: 'websocket_connection',
    name: 'WebSocket to Unknown Server',
    category: CATEGORY.NETWORK,
    severity: SEVERITY.HIGH,
    confidence: 0.6,
    regex: /new\s+WebSocket\s*\(\s*['"`]wss?:\/\//gi,
    description: 'WebSocket connections can maintain persistent channels for data exfiltration or receiving commands from a C2 server.',
    remediation: 'Verify the WebSocket destination. Unknown or obfuscated WebSocket URLs are red flags.',
  },
  {
    id: 'xmlhttprequest',
    name: 'XMLHttpRequest with Sensitive Data',
    category: CATEGORY.NETWORK,
    severity: SEVERITY.HIGH,
    confidence: 0.55,
    regex: /XMLHttpRequest|\.open\s*\(\s*['"]POST['"]/gi,
    description: 'XMLHttpRequest POST calls can be used to send stolen data to remote servers.',
    remediation: 'Inspect the URL and payload of the request. Verify it is not sending sensitive data.',
  },
  {
    id: 'axios_post',
    name: 'Axios POST with Data',
    category: CATEGORY.NETWORK,
    severity: SEVERITY.MEDIUM,
    confidence: 0.5,
    regex: /axios\s*\.\s*post\s*\(/gi,
    description: 'Axios POST requests may transmit stolen credentials, keys, or tokens to attacker servers.',
    remediation: 'Verify the endpoint URL and check what data is being sent.',
  },

  // ── File System Access ────────────────────────────────
  {
    id: 'env_file_read',
    name: '.env File Access',
    category: CATEGORY.FILE_ACCESS,
    severity: SEVERITY.CRITICAL,
    confidence: 0.9,
    regex: /(?:readFile|readFileSync|createReadStream)\s*\([^)]*\.env/gi,
    description: 'Reading .env files steals API keys, database credentials, and other secrets stored as environment variables.',
    remediation: 'Legitimate code reads .env via dotenv. Direct file reads of .env are suspicious.',
  },
  {
    id: 'ssh_directory',
    name: 'SSH Directory Access',
    category: CATEGORY.FILE_ACCESS,
    severity: SEVERITY.CRITICAL,
    confidence: 0.95,
    regex: /(?:~\/\.ssh|\/home\/[^/]+\/\.ssh|\.ssh\/(?:id_rsa|id_ed25519|known_hosts|authorized_keys|config))/gi,
    description: 'Accessing SSH keys allows attackers to impersonate you on servers, GitHub, and other SSH-authenticated services.',
    remediation: 'No legitimate npm package or project code should ever read your SSH directory.',
  },
  {
    id: 'browser_data',
    name: 'Browser Data / Cookie Access',
    category: CATEGORY.FILE_ACCESS,
    severity: SEVERITY.CRITICAL,
    confidence: 0.9,
    regex: /(?:\.config\/google-chrome|AppData\\Local\\Google|Login\s*Data|Cookies|\.mozilla\/firefox)/gi,
    description: 'Reading browser profile data can steal saved passwords, cookies, session tokens, and browsing history.',
    remediation: 'This is a clear indicator of info-stealer malware. Do not run this code.',
  },
  {
    id: 'wallet_files',
    name: 'Wallet File Access',
    category: CATEGORY.FILE_ACCESS,
    severity: SEVERITY.CRITICAL,
    confidence: 0.95,
    regex: /(?:solana|\.?phantom|\.?metamask|keystore|wallet\.dat|\.?ethereum|\.config\/solana|APPDATA[^)]*(?:MetaMask|Phantom|Ethereum|wallet))/gi,
    description: 'Accessing cryptocurrency wallet files can lead to theft of all funds in the wallet.',
    remediation: 'No third-party code should access wallet files. This is a confirmed wallet stealer.',
  },
  {
    id: 'aws_credentials',
    name: 'Cloud Credentials Access',
    category: CATEGORY.FILE_ACCESS,
    severity: SEVERITY.CRITICAL,
    confidence: 0.9,
    regex: /(?:\.aws\/credentials|\.kube\/config|\.docker\/config|gcloud\/credentials)/gi,
    description: 'Reading cloud credentials gives attackers access to your AWS, Kubernetes, Docker, or GCP infrastructure.',
    remediation: 'Legitimate code uses environment variables or IAM roles. Direct credential file reads are malicious.',
  },
  {
    id: 'readfile_generic',
    name: 'Suspicious File Read',
    category: CATEGORY.FILE_ACCESS,
    severity: SEVERITY.MEDIUM,
    confidence: 0.4,
    regex: /(?:readFile(?:Sync)?|createReadStream)\s*\(\s*(?:path\.join|path\.resolve)?\s*\(?.*(?:home|user|appdata)/gi,
    description: 'Reading files from user home directories may indicate data collection or credential theft.',
    remediation: 'Verify the specific files being read and ensure they are necessary for the application.',
  },

  // ── Process Execution ─────────────────────────────────
  {
    id: 'child_process_exec',
    name: 'child_process.exec()',
    category: CATEGORY.PROCESS,
    severity: SEVERITY.CRITICAL,
    confidence: 0.75,
    regex: /(?:child_process|require\s*\(\s*['"]child_process['"]\s*\))[\s\S]{0,60}(?:exec|execSync|spawn|spawnSync|execFile)\s*\(/gi,
    description: 'Running system commands can install additional malware, modify system settings, or exfiltrate data.',
    remediation: 'Verify what commands are being executed. Avoid running code that spawns unknown processes.',
  },
  {
    id: 'exec_direct',
    name: 'exec() / execSync() Call',
    category: CATEGORY.PROCESS,
    severity: SEVERITY.HIGH,
    confidence: 0.7,
    regex: /\b(?:exec|execSync|spawnSync)\s*\(\s*['"`]/gi,
    description: 'Direct execution of shell commands from JavaScript can perform any system-level action.',
    remediation: 'Inspect the command being executed. Be especially wary of piped commands and encoded payloads.',
  },
  {
    id: 'python_subprocess',
    name: 'Python subprocess/os.system',
    category: CATEGORY.PROCESS,
    severity: SEVERITY.HIGH,
    confidence: 0.7,
    regex: /(?:subprocess\.(?:run|call|Popen|check_output)|os\.system|os\.popen)\s*\(/gi,
    description: 'Python process execution functions can run arbitrary system commands.',
    remediation: 'Verify the commands being run. Never execute untrusted Python code with subprocess access.',
  },
  {
    id: 'reverse_shell',
    name: 'Reverse Shell Pattern',
    category: CATEGORY.PROCESS,
    severity: SEVERITY.CRITICAL,
    confidence: 0.98,
    regex: /(?:\/bin\/(?:sh|bash)|nc\s+-e|bash\s+-i|ncat|mkfifo|\/dev\/tcp\/|python\s+-c\s+['"]import\s+socket)/gi,
    description: 'Reverse shell commands give attackers interactive access to your machine. This is active exploitation.',
    remediation: 'STOP IMMEDIATELY. This is a confirmed attack payload. Do not run this code under any circumstances.',
  },
  {
    id: 'powershell_download',
    name: 'PowerShell Download Cradle',
    category: CATEGORY.PROCESS,
    severity: SEVERITY.CRITICAL,
    confidence: 0.95,
    regex: /powershell[\s\S]{0,40}(?:IEX|Invoke-Expression|DownloadString|DownloadFile|Net\.WebClient|Start-Process)/gi,
    description: 'PowerShell download cradles fetch and execute remote payloads — a primary malware delivery mechanism on Windows.',
    remediation: 'This is a known malware delivery pattern. Do not run this code.',
  },

  // ── Crypto / Wallet Specific ──────────────────────────
  {
    id: 'private_key_regex',
    name: 'Private Key Extraction',
    category: CATEGORY.CRYPTO,
    severity: SEVERITY.CRITICAL,
    confidence: 0.9,
    regex: /(?:0x[a-fA-F0-9]{64}|privateKey|private_key|secret_key|PRIVATE_KEY)[\s\S]{0,30}(?:send|post|fetch|axios|webhook)/gi,
    description: 'Extracting and transmitting private keys results in complete loss of wallet funds.',
    remediation: 'Never share or transmit private keys. Code that accesses and sends private keys is a wallet stealer.',
  },
  {
    id: 'seed_phrase',
    name: 'Seed Phrase / Mnemonic Access',
    category: CATEGORY.CRYPTO,
    severity: SEVERITY.CRITICAL,
    confidence: 0.85,
    regex: /(?:mnemonic|seed\s*phrase|recovery\s*phrase|bip39|word\s*list)[\s\S]{0,50}(?:split|match|send|post|fetch)/gi,
    description: 'Accessing seed phrases or mnemonics can allow attackers to reconstruct and drain your entire wallet.',
    remediation: 'Seed phrases should never be processed or transmitted by third-party code.',
  },
  {
    id: 'max_approval',
    name: 'Max Token Approval (uint256 max)',
    category: CATEGORY.CRYPTO,
    severity: SEVERITY.CRITICAL,
    confidence: 0.85,
    regex: /approve\s*\([^)]*(?:2\s*\*\*\s*256|MAX_UINT|ethers\.constants\.MaxUint256|0xffffffff|type\(uint256\)\.max)/gi,
    description: 'Approving maximum token spending allows the approved address to drain all tokens of that type from your wallet.',
    remediation: 'Only approve the exact amount needed. Never approve max uint256 to untrusted contracts.',
  },
  {
    id: 'set_approval_for_all',
    name: 'setApprovalForAll Drainer',
    category: CATEGORY.CRYPTO,
    severity: SEVERITY.CRITICAL,
    confidence: 0.9,
    regex: /setApprovalForAll\s*\(/gi,
    description: 'setApprovalForAll grants an address complete control over all your NFTs in a collection. Drainer contracts abuse this.',
    remediation: 'Only call setApprovalForAll on trusted, audited marketplaces. Verify the operator address.',
  },
  {
    id: 'transfer_from',
    name: 'transferFrom Pattern',
    category: CATEGORY.CRYPTO,
    severity: SEVERITY.HIGH,
    confidence: 0.6,
    regex: /transferFrom\s*\(\s*(?:msg\.sender|owner|victim)/gi,
    description: 'transferFrom with msg.sender as the source can drain tokens after approval.',
    remediation: 'Verify the contract logic. Ensure transferFrom is used properly with legitimate business logic.',
  },
  {
    id: 'ethers_wallet_exfil',
    name: 'Ethers Wallet + Exfiltration',
    category: CATEGORY.CRYPTO,
    severity: SEVERITY.CRITICAL,
    confidence: 0.92,
    regex: /(?:ethers\.Wallet|Wallet\.fromMnemonic|Wallet\.fromEncryptedJson)[\s\S]{0,100}(?:fetch|post|send|axios|webhook)/gi,
    description: 'Creating wallets from keys/mnemonics and then sending data externally is a wallet theft pattern.',
    remediation: 'Never allow code to create wallets and make network calls in the same flow without verification.',
  },
  {
    id: 'hardcoded_private_key',
    name: 'Hardcoded Private Key',
    category: CATEGORY.CRYPTO,
    severity: SEVERITY.HIGH,
    confidence: 0.75,
    regex: /(?:private[_]?key|secret[_]?key)\s*[:=]\s*['"`]0x[a-fA-F0-9]{64}['"`]/gi,
    description: 'Hardcoded private keys in code may be attacker addresses or indicate the code is designed to steal keys matching this format.',
    remediation: 'Private keys should never appear in source code. Use environment variables or secure vaults.',
  },

  // ── Social Engineering Indicators ─────────────────────
  {
    id: 'preinstall_script',
    name: 'Preinstall/Postinstall Script',
    category: CATEGORY.CODE_EXEC,
    severity: SEVERITY.HIGH,
    confidence: 0.7,
    regex: /["'](?:preinstall|postinstall|preuninstall)["']\s*:/gi,
    description: 'npm lifecycle scripts run automatically during installation, often used by malicious packages to execute payloads.',
    remediation: 'Inspect package.json scripts before running npm install. Use --ignore-scripts flag.',
  },
  {
    id: 'install_script_curl',
    name: 'curl/wget in Install Script',
    category: CATEGORY.PROCESS,
    severity: SEVERITY.CRITICAL,
    confidence: 0.9,
    regex: /(?:curl|wget)\s+(?:-[a-zA-Z]+\s+)*(?:https?:\/\/)/gi,
    description: 'Downloading and executing scripts from the internet during installation is a common malware delivery method.',
    remediation: 'Inspect the URL being downloaded. Never pipe curl output to sh/bash.',
  },
  {
    id: 'disable_security',
    name: 'Disable Security Instructions',
    category: CATEGORY.SOCIAL,
    severity: SEVERITY.HIGH,
    confidence: 0.8,
    regex: /(?:disable|turn\s*off|deactivate)\s+(?:antivirus|firewall|windows\s*defender|security|eslint|husky)/gi,
    description: 'Asking you to disable security tools is a major red flag. Legitimate code never requires disabling protection.',
    remediation: 'NEVER disable security tools for running third-party code. This is a social engineering tactic.',
  },
  {
    id: 'no_verify_flag',
    name: '--no-verify or Skip Validation',
    category: CATEGORY.SOCIAL,
    severity: SEVERITY.MEDIUM,
    confidence: 0.65,
    regex: /--no-verify|--ignore-scripts|NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*['"]?0/gi,
    description: 'Bypassing verification and security checks removes safety guardrails that protect against malicious behavior.',
    remediation: 'Never use --no-verify or disable TLS validation when working with untrusted code.',
  },
  {
    id: 'obfuscated_require',
    name: 'Obfuscated require/import',
    category: CATEGORY.CODE_EXEC,
    severity: SEVERITY.HIGH,
    confidence: 0.8,
    regex: /require\s*\(\s*(?:Buffer\.from|atob|String\.fromCharCode)/gi,
    description: 'Obfuscating module names in require() calls is used to hide the import of dangerous modules like child_process.',
    remediation: 'Decode the obfuscated module name. If it resolves to child_process, fs, net, or http — treat as malicious.',
  },
  {
    id: 'string_fromcharcode',
    name: 'String.fromCharCode Obfuscation',
    category: CATEGORY.CODE_EXEC,
    severity: SEVERITY.HIGH,
    confidence: 0.7,
    regex: /String\.fromCharCode\s*\(\s*\d+(?:\s*,\s*\d+){3,}/gi,
    description: 'Building strings from character codes is used to hide suspicious strings from pattern matching.',
    remediation: 'Evaluate the character codes to see what string they produce.',
  },
];

/**
 * Social engineering patterns for message analysis
 */
export const MESSAGE_PATTERNS = [
  {
    id: 'urgency',
    name: 'Urgency / Time Pressure',
    icon: '⏰',
    regex: /(?:ASAP|urgent|immediately|right\s*now|deadline\s*(?:is\s*)?today|time\s*sensitive|act\s*(?:fast|quickly|now)|limited\s*time|expir(?:es?|ing)|don'?t\s*(?:wait|delay|miss)|hurry)/gi,
    description: 'Creating artificial urgency is a classic pressure tactic to prevent you from verifying the opportunity.',
    advice: 'Take your time. Legitimate opportunities don\'t expire in hours.',
  },
  {
    id: 'compensation',
    name: 'Unrealistic Compensation',
    icon: '💰',
    regex: /(?:\$\d{3,}(?:\/|\s*per\s*)(?:hr|hour|day)|\$\d{4,}(?:\/|\s*per\s*)(?:week|wk)|(?:5|6|7)\s*figure|(?:100|200|300|500)k?\+?\s*(?:per|\/)\s*(?:year|month|annum)|earn\s*(?:up\s*to\s*)?\$\d{4,})/gi,
    description: 'Unrealistically high pay rates are used to lure victims into engaging with malicious projects.',
    advice: 'If the compensation seems too good to be true, it almost certainly is.',
  },
  {
    id: 'run_code_request',
    name: 'Request to Run Code',
    icon: '⚠️',
    regex: /(?:run\s*(?:this|the)\s*(?:code|script|project|app)|clone\s*(?:and|then)\s*run|npm\s*(?:install|start|run)|just\s*(?:run|execute|test)\s*it|try\s*(?:running|executing)|set\s*up\s*(?:the\s*)?project\s*(?:and|then)|git\s*clone)/gi,
    description: 'Asking you to run unknown code is the primary attack vector for code-based scams.',
    advice: 'NEVER run code from unknown sources. Always review it first or use a sandbox/VM.',
  },
  {
    id: 'impersonation',
    name: 'Impersonation Signals',
    icon: '🎭',
    regex: /(?:(?:i'?m|we'?re)\s*(?:from|with|at)\s*(?:Google|Meta|Facebook|Apple|Microsoft|Coinbase|Binance|OpenSea|Uniswap)|(?:official|verified)\s*(?:team|partner|representative)|(?:CEO|CTO|founder|co-founder)\s*(?:of|at)|hiring\s*(?:manager|team)\s*(?:at|from))/gi,
    description: 'Scammers impersonate employees of well-known companies to build trust.',
    advice: 'Verify the person\'s identity through official company channels, not through the link they provide.',
  },
  {
    id: 'private_communication',
    name: 'Move to Private Channel',
    icon: '🔒',
    regex: /(?:(?:DM|message|contact|reach)\s*(?:me|us)\s*(?:on|at|via)\s*(?:telegram|discord|whatsapp|signal)|let'?s?\s*(?:move|continue|discuss)\s*(?:this\s*)?(?:on|in|via)\s*(?:DM|private|telegram))/gi,
    description: 'Moving conversations to private channels reduces accountability and makes scams harder to report.',
    advice: 'Be cautious of anyone wanting to move discussions to unmonitored private channels.',
  },
  {
    id: 'nda_secrecy',
    name: 'NDA / Secrecy Requests',
    icon: '🤫',
    regex: /(?:NDA|non-?disclosure|confidential(?:ity)?|don'?t\s*(?:share|tell|mention)|keep\s*(?:this\s*)?(?:secret|private|between\s*us)|under\s*wraps)/gi,
    description: 'Requiring secrecy before any engagement is a tactic to prevent victims from seeking advice.',
    advice: 'Legitimate companies don\'t require NDAs before an initial conversation.',
  },
  {
    id: 'suspicious_links',
    name: 'Suspicious Links / Domains',
    icon: '🔗',
    regex: /(?:https?:\/\/(?:\w+\.)?(?:bit\.ly|t\.ly|tinyurl|shorturl|is\.gd|rb\.gy|cutt\.ly)|\.(?:xyz|tk|ml|ga|cf|gq|top|work|click|link|live|online|site|fun|icu|buzz)\b)/gi,
    description: 'Shortened URLs and suspicious TLDs are commonly used to disguise malicious destinations.',
    advice: 'Expand shortened URLs before clicking. Verify domains are legitimate.',
  },
  {
    id: 'crypto_payment',
    name: 'Crypto Payment Request',
    icon: '🪙',
    regex: /(?:send\s*(?:me|us)?\s*(?:some|a\s*(?:small|little))?\s*(?:ETH|BTC|SOL|USDT|crypto)|gas\s*fee|transaction\s*fee|(?:deposit|stake|invest)\s*(?:first|to\s*(?:start|begin|proceed))|pay\s*(?:the\s*)?(?:gas|fee))/gi,
    description: 'Asking for crypto payments upfront is a common advance-fee scam.',
    advice: 'Never send crypto to receive a job, opportunity, or "larger payment."',
  },
  {
    id: 'flattery',
    name: 'Excessive Flattery',
    icon: '🌟',
    regex: /(?:(?:your|the)\s*(?:work|portfolio|profile|skills)\s*(?:is|are)\s*(?:amazing|incredible|impressive|outstanding|exceptional)|(?:exactly|just)\s*(?:the\s*(?:person|developer)|what)\s*we(?:'re|\s*are)\s*looking\s*for|(?:perfect|ideal)\s*(?:fit|candidate|match))/gi,
    description: 'Excessive flattery is used to make victims feel special and lower their guard.',
    advice: 'Be skeptical of unsolicited praise from strangers who immediately follow up with an "opportunity."',
  },
  {
    id: 'github_repo_link',
    name: 'GitHub Repo to Clone',
    icon: '📦',
    regex: /(?:github\.com\/[a-zA-Z0-9_-]+\/[a-zA-Z0-9_-]+|check\s*(?:out|this)\s*(?:repo|repository|project)|(?:here'?s|this\s*is)\s*(?:the|our|my)\s*(?:repo|repository|project|code))/gi,
    description: 'Linking to GitHub repositories that contain malicious code in install scripts or dependencies.',
    advice: 'Always inspect package.json scripts and dependencies before cloning and installing.',
  },
];
